// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Route_Fare_Management.Infrastructure;

#nullable disable

namespace Route_Fare_Management.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260422175649_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Route_Fare_Management.Domain.PricingEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal?>("BusinessPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("BusinessSeats")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DayOfWeek")
                        .HasColumnType("int");

                    b.Property<decimal?>("EconomyPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("EconomySeats")
                        .HasColumnType("int");

                    b.Property<decimal?>("FirstClassPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("FirstClassSeats")
                        .HasColumnType("int");

                    b.Property<Guid>("TourOperatorRouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("TourOperatorRouteId", "Date")
                        .IsUnique();

                    b.ToTable("PricingEntries", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.Route", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Destination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("_availableBookingClasses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("AvailableBookingClasses");

                    b.HasKey("Id");

                    b.HasIndex("Origin", "Destination")
                        .IsUnique();

                    b.ToTable("Routes", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.Season", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Year", "Type")
                        .IsUnique();

                    b.ToTable("Seasons", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.TourOperator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("_supportedBookingClasses")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("")
                        .HasColumnName("SupportedBookingClasses");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("TourOperators", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.TourOperatorRoute", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("RouteId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SeasonId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TourOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("RouteId");

                    b.HasIndex("SeasonId");

                    b.HasIndex("TourOperatorId", "RouteId", "SeasonId")
                        .IsUnique();

                    b.ToTable("TourOperatorRoutes", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<Guid?>("TourOperatorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("TourOperatorId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.PricingEntry", b =>
                {
                    b.HasOne("Route_Fare_Management.Domain.TourOperatorRoute", "TourOperatorRoute")
                        .WithMany("PricingEntries")
                        .HasForeignKey("TourOperatorRouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TourOperatorRoute");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.TourOperatorRoute", b =>
                {
                    b.HasOne("Route_Fare_Management.Domain.Route", "Route")
                        .WithMany("TourOperatorRoutes")
                        .HasForeignKey("RouteId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Route_Fare_Management.Domain.Season", "Season")
                        .WithMany("TourOperatorRoutes")
                        .HasForeignKey("SeasonId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Route_Fare_Management.Domain.TourOperator", "TourOperator")
                        .WithMany("TourOperatorRoutes")
                        .HasForeignKey("TourOperatorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Route");

                    b.Navigation("Season");

                    b.Navigation("TourOperator");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.User", b =>
                {
                    b.HasOne("Route_Fare_Management.Domain.TourOperator", "TourOperator")
                        .WithMany("Members")
                        .HasForeignKey("TourOperatorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("TourOperator");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.Route", b =>
                {
                    b.Navigation("TourOperatorRoutes");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.Season", b =>
                {
                    b.Navigation("TourOperatorRoutes");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.TourOperator", b =>
                {
                    b.Navigation("Members");

                    b.Navigation("TourOperatorRoutes");
                });

            modelBuilder.Entity("Route_Fare_Management.Domain.TourOperatorRoute", b =>
                {
                    b.Navigation("PricingEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
